[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.intl",
  "php82Extensions.zip",
  "php82Extensions.exif",
  "php82Extensions.openssl"
]

[phases.install]
cmds = [
  "composer install --no-interaction --prefer-dist"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
